language: node_js
sudo: required
script:
  - ./_scripts/run-tests.sh
branches:
  except:
  - master
node_js:
 - '6.1'
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rvm install 2.1
  - rvm use 2.1
  - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
  - gem install bundler
  - bundle check || bundle install
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: iM+SRDQQ0dsvY/vmcwJGV9PNnw9jcIkeuzHKe2Yns2VFjVqdVBEKUaj/pUKSuykiGFtsiKGaT8QGIuXHyerBptb1syGfMlmR4d/83qWsJwyzjU9wo6v7GMRN912cigA+JUzoOqB1DbBbvi3Rw384q4SMTjLy7/5zOQqByuHjeiPh737Q07kmyEz25yXmym9Oir3grphmqcNN1++cWBLuX7UWOLe8sNT67A9hxdO0qeWVM38NOKMQF6W+Vz/7xThVegH0zAlCw3r2RCBmVNlwklIqOGIkz0Jrp5JMZwB9Zn0vs4O7MaPtoe0FCEKTpS8oDjRYrrjW2kof/D39F7zLsN05YJ6cksKBiAUqsCvnm49y9RVpWnXua8uythkB5rQsHhHK0h1BttbWcC4D+HkkRCbfbbEKNxy3K+UWfQICJOXkUZSrkkWuIT+MxYgHoI2y8e6Rcui2wMt48whTmnuawxdJ1E8W09kREH/fvXlZ3AR1pVhgwbYbLti9aR31pbt9ErPbVQ6iEvpUImk1Seuc/5LRBMIs9lHiHmgnkuR2HJaBUHdUAWuOgVK0VqThVwqgOwu6p075ODHm/uEXx7YIsE+lwdgh1ygmFYNAxUCSDcQAE0A7AS2VZtuznnliUx0/QGtYiJaSwAcvqq+ux42qhPqmry1ovnO71BSColUx2KQ=
  - secure: BCoOp3iOlF95dfvqjfReN4Y0dqGhFLRFJYIL0URtS0DsM717UooFg5JtPP53Ccr3H31MRu0cAunQObSCbVuBFfM3O/uD0ViyNNJVidj9Jl9blE5CxOKIHzzCXWrsk/HbqFaWHsyb1OXG5aMwnKeL3rHY5G8BjMWyaw5EMfdrgiBWpw8Exk8UeDLcsU4T7QSsCq0BuAnzaFCMRYAi4F8bPRWx0Xgvd+gwnzw+WrB+v4MgoU667WdKW02lwGMZxc82mkG9/wTjSz2+riMp0hQVgIP0/uMU4rDCXOVr8eNecGWFpEeMxF++5jvhIhkfjsL+01bHGqTCdDSMZLIUL+Fora1hgS5fYL7o/aScMppmRPyjk8bNZIRv7Vk/TOgctjlR4MWl51rb2CUL0dMbeOT1kkI0MqutTdLnFOOhyCxlYZWN8I8v+y0djJqBT9g3j89bDSJYwLMLlXfvb9hAUtbs3NURtM2sBfMkZG1MOL3jvDoCxeJoG68MxziI/vk3iVGvRqXS7RE05gy4tR77U2ZwT6QkxpLo9b5CKS4f1PMtll98D0Kk70HzuEo/r2KcOMXPZlww9u/ylGy5fqWpXwKkSn9t5lOsE6LbjC2oj8YRWnz8SsF3dOI+ApLN0qDpp/PxqotNu7GDw4sE5l/xZ5jfI+ZkJqknxr/l+eAJ8DFiVb0=
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: false
  on:
    branch: source