language: ruby
rvm:
  - 2.2
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - node -v
  - npm install -g gulp
  - npm install 
  - gem install jekyll
  - gulp build
script:
  - npm run travis
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer