language: ruby
rvm:
  - 2.2
before_script:
  - npm install -g gulp
  - npm install 
  - gem install jekyll
script: npm run travis
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer