# Build settings

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
    style: compressed
include: ["_pages"]
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  casestudy:
    output: true
    permalink: /casestudy/:path/
  service:
    output: true
    permalink: /service/:path/
  career:
    output: true
    permalink: /career/:path/

