# Build settings

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
    style: compressed
include: ["_pages"]
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  casestudy:
    output: true
    permalink: /casestudy/:path/
  service:
    output: true
    permalink: /service/:path/
  career:
    output: true
    permalink: /career/:path/
prose:
  media: 'assets/img/blog'
  metadata:
    _posts:
      - name: "description"
        field:
          label: "Description"
          element: "textarea"
          placeholder: "Enter a Description"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An awesome Headline!"
      - name: "layout"
        field:
          label: "Layout"
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          label: "Category"
          element: "text"
          value: "All"
      - name: "image"
        field:
          label: "Image Name"
          element: "text"
          value: "blog.jpg"
      - name: "tags"
        field:
          label: "Tag"
          element: "text"
          value: "all"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "author"
        field:
          label: "Author name"
          element: "select"
          value: "true"
          options:
             - name: 'Gopi'
               value: 'Gopi'
             - name: 'Palani'
               value: 'Palani'
             - name: 'Chandru'
               value: 'Chandru'
             - name: 'Keerthana'
               value: 'Keerthana'
    _portfolio:
       - name: "category"
         field:
          label: "Category"
          element: "select"
          value: "true"
          options:
             - name: 'BRANDING'
               value: 'BRANDING'
             - name: 'PACKAGING & LABEL'
               value: 'PACKAGING & LABEL'
             - name: 'ILLUSTRATION & ART'
               value: 'ILLUSTRATION & ART'
             - name: 'ANIMATION'
               value: 'ANIMATION'
             - name: 'WEB & MOBILE APP DESIGN'
               value: 'WEB & MOBILE APP DESIGN'
       - name: "project_title"
         field:
          label: "Title"
          element: "text"
          value: "Title"
       - name: "background-class"
         field:
          label: "background-class"
          element: "hidden"
          value: "portBgImg"
       - name: "porject_subtitle"
         field:
          label: "Description"
          element: "text"
          value: "Description"
       - name: "project_detail"
         field:
          label: "Project Detail"
          element: "textarea"
          placeholder: "Enter a Description"
       - name: "whatWeDoList"
         field:
          label: "What we do"
          element: "textarea"
          placeholder: "Enter a Description"
