backend:
  name: github
  repo: mcsekar123/mcsekar123.github.io # Path to your Github repository
  branch: master # Branch to update
  site_domain: littlebrahma.netlify.com # Your Netlify site address if different from host
media_folder: "assets/img"
collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "blog_description", widget: "string"}
      - {label: "Blog Image", name: "blog_image", widget: "image"}
      - {label: "Blog Highlight", name: "blog_highlight", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author_name", widget: "string"}
      - {label: "Author Img URL", name: "author_img", widget: "string"}
      - {label: "Author Title", name: "author_title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}