backend:
  name: github
  repo: mcsekar123/mcsekar123.github.io # Path to your Github repository
  branch: master # Branch to update
  site_domain: littlebrahma.netlify.com # Your Netlify site address if different from host
media_folder: "assets/img"
collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
       - {label: "Title", name: "blog_title", widget: "string"}
      - {label: "Description", name: "blog_description", widget: "string"}
      - {label: "Blog Image", name: "blog_image", widget: "image"}
      - {label: "Blog Highlight", name: "blog_highlight", widget: "string"}
      - {label: "Publish Date", name: "publish_date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author_name", widget: "string"}
      - {label: "Author Img URL", name: "author_image", widget: "string"}
      - {label: "Author Title", name: "author_title", widget: "string"}
      - {label: "Category", name: "blog_category", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog_detail"}